name: moonspace
description: MoonSpace
version: 0.0.1
homepage: https://github.com/CodeHariK/MoonSpace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.11.0
  meta: ^1.16.0

  go_router: ^15.2.0

  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15
  hooks_riverpod: ^3.0.0-dev.15

  shared_preferences: ^2.2.2

  feedback: ^3.1.0

  smooth_sheets: ^0.12.0
  flutter_custom_carousel: ^0.1.0+1
  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.15
  build_runner: ^2.4.7
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.15

flutter:
  generate: true
