name: moonspace
description: MoonSpace
version: 0.0.1
homepage: https://github.com/CodeHariK/MoonSpace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.11.0
  meta: ^1.10.0
  rxdart: ^0.28.0
  flutter_animate: ^4.3.0

  go_router: ^15.1.2
  go_router_builder: ^2.4.0

  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15
  hooks_riverpod: ^3.0.0-dev.15

  shared_preferences: ^2.2.2

  feedback: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.15
  build_runner: ^2.4.7
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.15

flutter:
  generate: true
